### ISSUE TITLE
Wrong display of blog item date

### ISSUE THREAD

**Issue by johmoh** [getgrav/grav-theme-twentyfifteen#1]
**IF** a blog item is date is e.g. 01/29/2015 (MM/DD/YYYY)
**THEN** blog item date "September 1, 2015" (at the moment it is September 2015 so the month might be the current month)

Currently a blog item date is displayed as:
CURRENT_MONTH_TEXT ITEM_DATE_MONTH_NUMBER, ITEM_DATE_YEAR

I will fix that bug.

**Comment by hexplor** [comment]
Thanks :+1:  Merged :)  I will include that in next release :)
